export const CATEGORIES_ACTION_TYPES = {
  SET_CATEGORIES: "SET_CATEGORIES",
  SET_CATEGORIES_START: "SET_CATEGORIES_START",
  SET_CATEGORIES_SUCCESS: "SET_CATEGORIES_SUCCESS",
  SET_CATEGORIES_FAILED: "SET_CATEGORIES_FAILED",
};
